# Generated by Django 6.0.7 on 2026-08-25 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARGUS_app', '0008_alter_alert_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='health_score',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='health_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('OFFLINE', 'Offline'), ('CRITICAL', 'Critical')], default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('NORMAL', 'Normal')], max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_performed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_maintenance', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='ARGUS_app.vehicle')),
            ],
        ),
    ]
