# Generated by Django 6.0.7 on 2026-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARGUS_app', '0009_sensorreading_health_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar')], default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_system',
            field=models.CharField(choices=[('KM', 'Kilometers'), ('MILES', 'Miles')], default='KM', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_critical_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_warning_email',
            field=models.BooleanField(default=False),
        ),
    ]
