# Generated by Django 6.0.7 on 2026-07-22 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARGUS_app', '0004_sensorreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=30)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ARGUS_app.sensorreading')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ARGUS_app.vehicle')),
            ],
        ),
    ]
