# Generated by Django 6.0.7 on 2026-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARGUS_app', '0005_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='health_score',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('HIGH_TEMPERATURE', 'High Temperature'), ('HIGH_VIBRATION', 'High Vibration'), ('LOW_HEALTH_SCORE', 'Low Health Score')], max_length=30),
        ),
    ]
