# Generated by Django 6.0.7 on 2026-07-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARGUS_app', '0006_remove_sensorreading_health_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default=Warning, max_length=20),
            preserve_default=False,
        ),
    ]
