# Generated by Django 6.0.7 on 2026-07-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARGUS_app', '0007_remove_alert_vehicle_alert_severity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('HIGH_TEMPERATURE', 'High Temperature'), ('HIGH_VIBRATION', 'High Vibration'), ('LOW_HEALTH_SCORE', 'Low Health Score')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
